# put your configuration values here

[runtime]
log_level="WARNING"  # the system log level of data_load_tool
# use the dlthub_telemetry setting to enable/disable anonymous usage data reporting, see https://dlthub.com/docs/reference/telemetry
