[flake8]
ignore=E1,E2,E3,E4,F401,W391,W292,E501,E731,F811,W503,E704, W504
banned-modules = datetime = use data_load_tool.common.pendulum
                 json = use data_load_tool.common.json
                 decimal = use data_load_tool.common.decimal
                 decimal.Decimal = use data_load_tool.common.Decimal
                 open = use data_load_tool.common.open
                 pendulum = use data_load_tool.common.pendulum
                 typing.TypedDict = use data_load_tool.common.typing.TypedDict
                 typing-extensions.TypedDict = use data_load_tool.common.typing.TypedDict
extend-immutable-calls = data_load_tool.sources.incremental
per-file-ignores =
    tests/*: T20
    docs/*: T20