"""data load tool (data_load_tool) — the open-source Python library for data loading

How to create a data loading pipeline with data_load_tool in 3 seconds:

1. Write a pipeline script
>>> import data_load_tool
>>> from data_load_tool.sources.helpers import requests
>>> data_load_tool.run(requests.get("https://pokeapi.co/api/v2/pokemon/").json()["results"], destination="duckdb", table_name="pokemon")

2. Run your pipeline script
  > $ python pokemon.py

3. See and query your data with autogenerated Streamlit app
  > $ data_load_tool pipeline dlt_pokemon show

Or start with our pipeline template with sample PokeAPI (pokeapi.co) data loaded to bigquery

  > $ data_load_tool init pokemon bigquery

For more detailed info, see https://dlthub.com/docs/getting-started
"""

from data_load_tool.version import __version__
from data_load_tool.common.configuration.accessors import config, secrets
from data_load_tool.common.typing import TSecretValue as _TSecretValue, TSecretStrValue as _TSecretStrValue
from data_load_tool.common.configuration.specs import CredentialsConfiguration as _CredentialsConfiguration
from data_load_tool.common.pipeline import source_state as state
from data_load_tool.common.schema import Schema

from data_load_tool import sources
from data_load_tool.extract.decorators import source, resource, transformer, defer
from data_load_tool.destinations.decorators import destination

from data_load_tool.pipeline import (
    pipeline as _pipeline,
    run,
    attach,
    Pipeline,
    dbt,
    current as _current,
    mark as _mark,
)
from data_load_tool.pipeline import progress
from data_load_tool import destinations

pipeline = _pipeline
current = _current
mark = _mark

TSecretValue = _TSecretValue
"When typing source/resource function arguments it indicates that a given argument is a secret and should be taken from data_load_tool.secrets."

TSecretStrValue = _TSecretStrValue
"When typing source/resource function arguments it indicates that a given argument is a secret STRING and should be taken from data_load_tool.secrets."

TCredentials = _CredentialsConfiguration
"When typing source/resource function arguments it indicates that a given argument represents credentials and should be taken from data_load_tool.secrets. Credentials may be a string, dictionary or any other type."

__all__ = [
    "__version__",
    "config",
    "secrets",
    "state",
    "Schema",
    "source",
    "resource",
    "transformer",
    "defer",
    "destination",
    "pipeline",
    "run",
    "attach",
    "Pipeline",
    "dbt",
    "progress",
    "current",
    "mark",
    "TSecretValue",
    "TCredentials",
    "sources",
    "destinations",
]

# verify that no injection context was created
from data_load_tool.common.configuration.container import Container as _Container

assert (
    _Container._INSTANCE is None
), "Injection container should not be initialized during initial import"
# create injection container
_Container()
